<?php declare(strict_types = 1);

/**
 * @file
 * Provides a digi book entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;


/**
 * Implements hook_theme()
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return \array[][]
 */

 function digi_book_theme($existing, $type, $theme, $path) {
  return [
    'books_management' => [
      'variables' => [
        'user' => NULL,
        'books'=>[],
      ],
    ],
  ];
}

/**
 * Prepares variables for digi book templates.
 *
 * Default template: digi-book.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the digi book information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_digi_book(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function digi_book_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish digi books.
      $storage = \Drupal::entityTypeManager()->getStorage('digi_book');
      $digi_book_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($digi_book_ids) as $digi_book) {
        $digi_book->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize digi books.
      $storage = \Drupal::entityTypeManager()->getStorage('digi_book');
      $digi_book_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($digi_book_ids) as $digi_book) {
        $digi_book->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function digi_book_user_predelete(UserInterface $account): void {
  // Delete digi books that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('digi_book');
  $digi_book_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($digi_book_ids)
  );
}

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function digi_book_form_digi_book_copy_book_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $book_id = \Drupal::request()->query->get('book');
  if(!empty($book_id)){
    // Récupération du livre
    $entity_book = \Drupal::entityTypeManager()->getStorage('digi_book')->load($book_id);
    // Modification du champ de selection de livre
    $form['field_book']['widget']['#disabled'] = TRUE;
    $form['field_book']['widget'][0]['target_id']['#default_value'] = $entity_book;


    // Modification du champ label
    $form['label']['widget'][0]['value']['#default_value'] = $entity_book->label();
  }else{
    $form['#prefix'] = '<h2>Attention vous, devez ajouté des exemplaires depuis la <a href="manage-book">gestion des livres</a></h2>';
  }
}